package co.com.edu.usbcali.abet;
// Generated 1/09/2015 07:32:31 PM by Zathura powered by Hibernate Tools 3.2.4.GA



/**
 * DetalleRubrica generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class DetalleRubrica  implements java.io.Serializable {


     private Long idDetalleRubrica;
     private Rubrica rubrica;

    public DetalleRubrica() {
    }

	
    public DetalleRubrica(Long idDetalleRubrica) {
        this.idDetalleRubrica = idDetalleRubrica;
    }
    public DetalleRubrica(Long idDetalleRubrica, Rubrica rubrica) {
       this.idDetalleRubrica = idDetalleRubrica;
       this.rubrica = rubrica;
    }
   
    public Long getIdDetalleRubrica() {
        return this.idDetalleRubrica;
    }
    
    public void setIdDetalleRubrica(Long idDetalleRubrica) {
        this.idDetalleRubrica = idDetalleRubrica;
    }
    public Rubrica getRubrica() {
        return this.rubrica;
    }
    
    public void setRubrica(Rubrica rubrica) {
        this.rubrica = rubrica;
    }




}


