package co.com.edu.usbcali.abet;
// Generated 1/09/2015 07:32:31 PM by Zathura powered by Hibernate Tools 3.2.4.GA



/**
 * OutcomePorCurso generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class OutcomePorCurso  implements java.io.Serializable {


     private Long idOutcomePorCurso;
     private Outcome outcome;
     private Curso curso;
     private String detalle;

    public OutcomePorCurso() {
    }

	
    public OutcomePorCurso(Long idOutcomePorCurso) {
        this.idOutcomePorCurso = idOutcomePorCurso;
    }
    public OutcomePorCurso(Long idOutcomePorCurso, Outcome outcome, Curso curso, String detalle) {
       this.idOutcomePorCurso = idOutcomePorCurso;
       this.outcome = outcome;
       this.curso = curso;
       this.detalle = detalle;
    }
   
    public Long getIdOutcomePorCurso() {
        return this.idOutcomePorCurso;
    }
    
    public void setIdOutcomePorCurso(Long idOutcomePorCurso) {
        this.idOutcomePorCurso = idOutcomePorCurso;
    }
    public Outcome getOutcome() {
        return this.outcome;
    }
    
    public void setOutcome(Outcome outcome) {
        this.outcome = outcome;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


